d500_node:
  ros__parameters:
    port: "/dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.1.1:1.0"
    baudrate: 230400

    frame_id: "lidar_360_link"
    topic_name: "/scan"

    range_min: 0.03
    range_max: 12.0
    scan_frequency: 10.0

    clockwise: true
    angle_offset_deg: 0.0
    bins: 720
